[package]
name = "vdf"
version = "0.1.0"
edition = "2021"

[dependencies]
jf-vdf = { git = "https://github.com/zilong-dai/PlonkExt.git", branch = "dev" }
ark-std = { workspace = true }
ark-bls12-381 = { workspace = true }
